name: gtoc8
channels:
- poliastro
dependencies:
- alabaster=0.7.3=py27_0
- astropy=1.0.2=np19py27_0
- babel=1.3=py27_0
- cairo=1.12.18=4
- certifi=14.05.14=py27_0
- coverage=3.7.1=py27_0
- docutils=0.12=py27_0
- enum34=1.0.4=py27_0
- fontconfig=2.11.1=4
- freetype=2.5.2=2
- funcsigs=0.4=py27_0
- ipython=3.1.0=py27_0
- ipython-notebook=3.1.0=py27_1
- jinja2=2.7.3=py27_1
- jplephem=1.2=np19py27_0
- jsonschema=2.4.0=py27_0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- libxml2=2.9.0=0
- llvmlite=0.5.0=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_2
- mistune=0.5.1=py27_1
- numba=0.19.1=np19py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.1=np19py27_0
- pip=7.0.3=py27_0
- pixman=0.26.2=0
- poliastro=0.3.0=np19py27_1
- ptyprocess=0.4=py27_0
- py=1.4.27=py27_0
- py2cairo=1.10.0=py27_2
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.3=py27_1
- pytest=2.7.1=py27_0
- python=2.7.10=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.4=py27_0
- pyzmq=14.6.0=py27_0
- qt=4.8.6=3
- readline=6.2=2
- scipy=0.15.1=np19py27_0
- setuptools=17.0=py27_0
- sip=4.16.5=py27_0
- six=1.9.0=py27_0
- snowballstemmer=1.2.0=py27_0
- sphinx=1.3.1=py27_0
- sphinx_rtd_theme=0.1.7=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- system=5.8=2
- terminado=0.5=py27_0
- tk=8.5.18=0
- tornado=4.2=py27_0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - cov-core==1.15.0
  - pytest-cov==1.8.1
  - sphinx-rtd-theme==0.1.7

